- hosts: localhost
  vars: 
    projectDir: '{{ playbook_dir | dirname }}'
    deployApp: "{{ lookup('env', 'DEPLOY_APP') | default(false) | bool }}"
    twineUsername: '{{ lookup("env", "TWINE_USERNAME") }}'
    twinePassword: '{{ lookup("env", "TWINE_PASSWORD") }}'
    dockerRepository: 'lukepafford/lukepafford_blog'
  tasks:
    - name: Ensure all tests pass
      command: pytest
      args:
        chdir: '{{ projectDir }}'
      register: pytestResults
      failed_when: pytestResults.rc not in [0, 5]

    - name: Ensure flake8 passes
      command: flake8
      args:
        chdir: '{{ projectDir }}'

    - import_tasks: build.yml
      when: deployApp


- import_playbook: static_files.yml
  vars:
    projectDir: '{{ playbook_dir | dirname }}'
  tags: static

- hosts: app
  become: true
  tasks:
    - name: Restart the app
      service:
        name: lukepafford_blog
        state: restarted
        enabled: yes
